spring.datasource.url=jdbc:postgresql://localhost:5432/concertbooking_test
spring.datasource.username=postgres
spring.datasource.password=1234

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
